# Generated by Django 2.0.7 on 2018-07-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_compare', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
