# Generated by Django 2.0.2 on 2018-07-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_compare', '0002_auto_20180730_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='course_compare.Course'),
        ),
    ]
